apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../components/custom-image
  - ../../components/label-studio
  - ../../components/minio
  - ../../components/yolo-api/base
  - ../../components/pipelines
