apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../gpus

patches:
  - target:
      group: autoscaling.openshift.io
      kind: ClusterAutoscaler
      name: default
    patch: |-
      - op: replace
        path: /spec/resourceLimits/gpus/0/type
        value: nvidia-gpu
