apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ml-demo

resources:
  - ../../components/minio
  - ../../components/demos/label-studio/overlays/flyingthings
  - link-github.yaml
  - namespace.yaml
