apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ml-demo

resources:
  - ../../components/custom-image
  - ../../components/label-studio
  - ../../components/minio
  - ../../components/yolo-api/base
  - ../../pipelines/manifests
  - ../../pipelines/tasks
  - link-github.yaml
  - namespace.yaml
  - ns-rb-view.yaml
