{
 "title": "model_corrective_candidates",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Video Frames w/ Zero Model Correction Candidates",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "noCorrectiveCandidates_total{}" }
   ]
  },
  { "title": "Model Corrective Candidates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total Video Frames Flagged for Correction",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modelCorrectiveCandidates_total{}"
    }
   ]
  },
  {
   "title": "Model Corrective Candidate Reasons",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "correctionReason_total{}" }
   ]
  },
  {
   "title": "Correction Candidate Reasons",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "correctionReason_total{}" }
   ]
  }
 ]
}