---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: job-setup-cluster-
  name: job-setup-cluster
  # annotations:
  #   argocd.argoproj.io/hook: Sync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: job-setup-cluster
          # image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
          image: registry.redhat.io/openshift4/ose-cli
          command:
            - /bin/bash
            - -c
            - /scripts/job.sh
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: job-setup-cluster
            defaultMode: 0755
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      serviceAccount: cluster-admin-minion
      serviceAccountName: cluster-admin-minion
