---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin-minion
  namespace: adhoc-ops
  annotations:
    NOT-FOR-PRODUCTION: EVER
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-minion
  annotations:
    NOT-FOR-PRODUCTION: EVER
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: cluster-admin-minion
    namespace: adhoc-ops
