apiVersion: v1
kind: Namespace
metadata:
  name: registry
  annotations:
    openshift.io/description: |
      A container registry
    openshift.io/display-name: Registry
  labels:
    argocd.argoproj.io/managed-by: cluster-config