apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: registry-viewer-all
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: registry-viewer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:anonymous
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:unauthenticated
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
