---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: centos
spec:
  tags:
  - name: stream9
    from:
      kind: DockerImage
      name: quay.io/centos/centos:stream9
    referencePolicy:
      type: Local
  - name: latest
    from:
      kind: ImageStreamTag
      name: centos:stream9
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: yolo-api-docker-centos
  annotations:
    app.openshift.io/vcs-ref: main
    app.openshift.io/vcs-uri: https://github.com/redhat-na-ssa/flyingthings.git
  labels:
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: '3.9'
spec:
  output:
    to:
      kind: ImageStreamTag
      name: yolo-api:docker-centos
  runPolicy: SerialLatestOnly
  source:
    contextDir: components/demo/yolo-api/container
    git:
      ref: cory-review
      uri: https://github.com/redhat-na-ssa/flyingthings.git
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
      from:
        kind: ImageStreamTag
        name: centos:stream9
    type: Docker
  triggers:
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange
