apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../toleration

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 6
