apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-classfile
spec:
  params:
    - name: NAMESPACE
      type: string
    - name: IMAGE
      type: string
      default: ubi9:latest
  steps:
    - name: create-classfile
      image: $(params.IMAGE)
      script: |
        cd $(workspaces.workspace.path)

        SOURCE_DIR=$(workspaces.source.path)
        BASEDIR=${SOURCE_DIR}/source/training
        
        cd datasets \
        
        $(workspaces.source.path)/source/training/create-classfile.sh && \
        cat classes.yaml && \
        mv classes.yaml $(workspaces.workspace.path)

        pwd && ls -al
  workspaces:
    - name: workspace
      mountPath: /opt/app-root/src/simplevis-data/workspace
    - name: source
      mountPath: /source
