apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: push-results
spec:
  params:
    - name:MODEL_WEIGHTS
      type: string
    - name: MINIO_ENDPOINT
      type: string
    - name: MINIO_BUCKET
      type: string
    - name: MINIO_ACCESSKEY
      type: string
    - name: MINIO_SECRETKEY
      type: string
    - name: NAMESPACE
      type: string
    - name: IMAGE
      type: string
      default: ubi9:latest
  steps:
    - name: push-results
      image: $(params.IMAGE)
      script: |
        cd $(workspaces.workspace.path)

        SOURCE_DIR=$(workspaces.source.path)
        BASEDIR=${SOURCE_DIR}/pipelines/scripts

        source $(workspaces.source.path)/pipelines/scripts/functions.sh && \
        minio_push_results

        pwd && ls -al
      env:
        - name:MODEL_WEIGHTS
          value: $(params.MODEL_WEIGHTS)
        - name: MINIO_ENDPOINT
          value: $(params.MINIO_ENDPOINT)
        - name: MINIO_BUCKET
          value: $(params.MINIO_BUCKET)
        - name: MINIO_ACCESSKEY
          value: $(params.MINIO_ACCESSKEY)
        - name: MINIO_SECRETKEY
          value: $(params.MINIO_SECRETKEY)
  workspaces:
    - name: workspace
      mountPath: /opt/app-root/src/simplevis-data/workspace
    - name: source
      mountPath: /source
