apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../default

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/tolerations
        value:
          - key: nvidia.com/gpu
            operator: Exists
            effect: NoSchedule
