kind: Secret
apiVersion: v1
metadata:
  name: htpasswd-workshop
  namespace: openshift-config
stringData:
  htpasswd: |
    # add a user / password with the following
    # NOTE: the leading extra space so you do not leave a password in shell history
    #  PASSWORD=alongsecret
    # echo -n "$PASSWORD" | htpasswd -inB admin
    # or
    # htpasswd -nB admin
type: Opaque
