apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/cluster-configs/login/overlays/htpasswd?ref=v0.18
- htpasswd-secret.yaml

patches:
  - path: patch-idp.yaml
    target:
      group: config.openshift.io
      kind: OAuth
      name: cluster
