apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: ClusterPolicy
      name: gpu-cluster-policy
    patch: |-
      - op: add
        path: /spec/devicePlugin/config/name
        value: device-plugin-config
      - op: add
        path: /spec/devicePlugin/config/default
        value: Tesla-T4-time-sliced
      - op: replace
        path: /spec/gfd/enabled
        value: true
  - target:
      kind: ConfigMap
      name: device-plugin-config
    patch: |-
      - op: add
        path: /data
        value:
          Tesla-T4-time-sliced: |-
            version: v1
            sharing:
              timeSlicing:
                resources:
                  - name: nvidia.com/gpu
                    replicas: 2