apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../default

patches:
  - target:
      group: org.eclipse.che
      kind: CheCluster
      name: devspaces
    patch: |-
      - op: replace
        path: /spec/devEnvironments/secondsOfRunBeforeIdling
        value: 300
