apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: yolo-api-s2i
  annotations:
    app.openshift.io/vcs-ref: main
    app.openshift.io/vcs-uri: https://github.com/redhat-na-ssa/flyingthings.git
  labels:
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: '3.9-ubi9'
spec:
  output:
    to:
      kind: ImageStreamTag
      name: yolo-api:custom
  runPolicy: SerialLatestOnly
  source:
    contextDir: /artifacts
    git:
      ref: main
      uri: https://github.com/redhat-na-ssa/flyingthings.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: yolo-api:latest
    type: Source
  triggers:
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange
