apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../default

patches:
  - target:
      kind: ClusterRoleBinding
      name: self-provisioners
    patch: |
      - op: replace
        path: /subjects
        value:
  - target:
      kind: LimitRange
      name: limit-range
      namespace: sandbox
    patch: |-
      - op: replace
        path: /spec/limits
        value:
          - default:
              cpu: 100m
              memory: 256Mi
            type: Container
