apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: label-studio
  annotations:
    app.openshift.io/vcs-ref: openshift
    app.openshift.io/vcs-uri: https://github.com/redhat-na-ssa/demo-ocp-label-studio.git
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: docker.io/heartexlabs/label-studio:latest
    from:
      kind: DockerImage
      name: docker.io/heartexlabs/label-studio:latest
    name: latest
    referencePolicy:
      type: Local
  - annotations:
      openshift.io/imported-from: docker.io/heartexlabs/label-studio:ubi_latest
    from:
      kind: DockerImage
      name: docker.io/heartexlabs/label-studio:ubi_latest
    name: ubi_latest
    referencePolicy:
      type: Local
