apiVersion: v1
kind: Service
metadata:
  name: label-studio
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: label-studio
    deployment: label-studio
  sessionAffinity: None
  type: ClusterIP
