apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - 00-operators
  # - 01-operator-configs
  - 02-components
  - demo-devspaces-nvidia-gpu-autoscale
  - tekton-operator

patches:
  - target:
      kind: ConsoleNotification
      name: banner-demo
    patch: |-
      - op: replace
        path: /spec/text
        value: 'DEMO: Flyingthings on OpenShift w/ GPUs'
