apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/codekow/demo-ai-gitops-catalog/components/configs/kustomized/minio/overlays/known-password?ref=main

patches:
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: minio
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 10Gi
