apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      group: nfd.openshift.io
      kind: NodeFeatureDiscovery
    path: patch-node-feature-discovery.yaml
