apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: github-ai-devspaces
spec:
  href: 'https://github.com/redhat-na-ssa/flyingthings'
  location: ApplicationMenu
  text: GitHub - Flying Things
  applicationMenu:
    section: Git Repos
    imageURL: https://img.icons8.com/fluency/512/github.png
