apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: flyingthings-notebook

resources:
  - ../../base

patches:
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: notebook
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 10Gi
  - target:
      group: apps
      kind: Deployment
      name: notebook
    path: patch-deployment.yaml
