apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devspaces

resources:
  - ../../base

patches:
  - target:
      group: org.eclipse.che
      kind: CheCluster
      name: devspaces
    patch: |-
      - op: replace
        path: /spec/components/dashboard/headerMessage/show
        value: true
      - op: replace
        path: /spec/components/dashboard/headerMessage/text
        value: |
          Please be patient... GPUs may take up to 12 min to be available!
      - op: replace
        path: /spec/devEnvironments/startTimeoutSeconds
        value: 720
