apiVersion: apps/v1
kind: Deployment
metadata:
  name: nvidia-vector-add
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nvidia-vector-add
  template:
    metadata:
      labels:
        app: nvidia-vector-add
    spec:
#      tolerations:
#        - key: nvidia.com/gpu
#          operator: Exists
#          effect: NoSchedule
      containers:
        - name: cuda-sample-vector-add
          image: "nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda11.7.1-ubuntu20.04"
          command: ["/bin/bash", "-c", "--"]
          args:
            - while true; do /cuda-samples/vectorAdd; done
          resources:
            limits:
              nvidia.com/gpu: 1
